-- Enable Row Level Security on all application tables.
-- Mainline accesses PostgreSQL exclusively via Prisma with direct database credentials.
-- Enabling RLS prevents unauthorized read/write access via Supabase PostgREST Data API.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ResearchConsent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AccountPurgeLedger" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AllowlistEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApiCallBudget" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlatformConnection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChessProfileSnapshot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImportedGame" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AnalysisResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JobRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LichessPuzzle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ResourceRef" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Assessment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConstraintSet" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Program" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProgramItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecommendationExposure" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ActivityEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingFeedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductFeedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingFeedbackPrompt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SkillState" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SkillStateSnapshot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ScheduleState" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PracticeItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TablebaseCache" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AdaptationLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingPreferenceState" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WeeklyFocus" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WeeklyAvailability" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AvailabilityOverride" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProgramDayForecast" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProgramRevision" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RewardEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationPref" ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS "_prisma_migrations" ENABLE ROW LEVEL SECURITY;

-- Defense in depth: revoke direct access from PostgREST client roles if they exist.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
    REVOKE ALL ON ALL ROUTINES IN SCHEMA public FROM anon;
  END IF;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated;
    REVOKE ALL ON ALL ROUTINES IN SCHEMA public FROM authenticated;
  END IF;
END $$;
