// The Methodology layer's public surface (BUILD.md §2.3). The Engine (engine/, server/,
// app/, analysis/) imports the loader, the provider pure functions, and the types from
// here — never the schema internals or config JSON directly. This is the typed boundary
// across which science enters the system (VISION §4).

export {
  loadMethodology,
  ACTIVE_METHODOLOGY_VERSION,
  DEFAULT_METHODOLOGY_VERSION,
  UnknownMethodologyVersionError,
} from "@/methodology/loader";

export {
  METHODOLOGY_RELEASES,
  methodologyReleaseFor,
  type MethodologyReleaseChannel,
  type MethodologyReleaseMetadata,
} from "@/methodology/releases";

export {
  nextCalibrationItem,
  scoreCalibration,
  buildImplementationIntention,
  // Seam 9 (engagement, M9): the reward-event policy reader the engine event bus calls.
  engagementEventsFor,
  // Program-engine seams (M6): Seams 1/3/4/5/7/8 pure reader functions.
  bandForRating,
  interpretGameFeatures,
  confidenceFromSampleSize,
  mapWeaknessToActivities,
  interfaceAffordancesFor,
  // Seam 4 §4.2–4.4 (M14): book-study + 2D/3D-modality readers for the deliberately-external layer.
  recommendBooks,
  woodpeckerSchedule,
  bookDifficultyFeedback,
  modalityRecommendation,
  targetPuzzleRating,
  practiceStructure,
  useWorkedExample,
  allocationUnitForActivity,
  prioritizeDailyMix,
  selectWeeklyFocus,
  shouldReviseWeeklyFocus,
  rollUpTrainingPreferences,
  updateTrainingPreferences,
  selectTrainingFitPrompt,
  rationaleFor,
  // Seam 6 (scheduling) + Measurement seams (M7): the adaptation-loop reader functions.
  gradeFromOutcome,
  newItemScheduleGrade,
  scheduleReview,
  redoFlowPolicy,
  detectPlateau,
  isProgressReal,
  isStableBaseline,
  // Measurement seam (M8): per-band expectation copy for the transparency dashboard.
  expectationForBand,
  // Seam 4 §4.1: structured game analysis protocol functions
  gameAnalysisProtocol,
  filterEngineLines,
  selectGamesForAnalysis,
  detectTilt,
  gameSelectionRatioFor,
  type GradedExpectation,
  type EngagementStateChange,
  type EngagementEvent,
  type RewardEventType,
  type CalibrationResponse,
  type NextCalibrationItem,
  type CalibrationEstimate,
  type IfThenPlan,
  type Band,
  type Track,
  type Confidence,
  type PracticeStructureKind,
  type WeaknessSignal,
  type CandidateActivity,
  type CandidateBookResource,
  type BoardAffordances,
  type BookRecommendation,
  type WoodpeckerCycle,
  type WoodpeckerSchedule,
  type BookDifficultyVerdict,
  type BookDifficultyFeedback,
  type ModalityRecommendation,
  type TargetFocus,
  type ScoredCandidate,
  type WeeklyFocusInput,
  type WeeklyFocusSelection,
  type WeeklyFocusRevisionInput,
  type FocusAlternative,
  type FocusRationaleSnapshot,
  type TrainingFeedbackRelevance,
  type TrainingFeedbackEnjoyment,
  type TrainingFeedbackTimeFit,
  type TrainingFitObservation,
  type TrainingFitPreferenceRollup,
  type TrainingFitPromptInput,
  type TrainingFitPrompt,
  type MixPreferences,
  type DueItem,
  type ActivityAllocationUnit,
  type PuzzleTarget,
  type FsrsGrade,
  type FsrsState,
  type RedoFlowPolicy,
  type RatingPoint,
  type PlateauResult,
  // Seam 4 §4.1: structured game analysis protocol types
  type CriticalMoment,
  type FilteredLine,
  type SRSPuzzle,
  type SuggestedGame,
  type TiltState,
  type EngineLine,
  type RecentGame,
  type RecentResult,
} from "@/methodology/provider";

export type {
  MethodologyConfig,
  AssessmentConfig,
  CalibrationConfig,
  CalibrationTrack,
  BandDefinition,
  SkillDimension,
  InterpretationConfig,
  ActivityDefinition,
  WeaknessResourceRule,
  DifficultyConfig,
  SchedulingConfig,
  PrioritizationConfig,
  WeeklyFocusConfig,
  TrainingFitConfig,
  EngagementConfig,
  EngagementEventRule,
  MeasurementConfig,
  RationaleEntry,
  AnchorSource,
  GameAnalysisConfig,
  EmotionalCalibrationConfig,
  ActiveReproductionConfig,
  RplFilteringConfig,
  SrsIntegrationConfig,
  GameSelectionConfig,
  TiltTriggerConfig,
  BookStudyConfig,
  BookRec,
  BookCategory,
  ModalityConfig,
} from "@/methodology/schema/config";

export type {
  Grade,
  Tier,
  GradedFlag,
  GradedValue,
} from "@/methodology/schema/graded";
